### ISSUE TITLE
Public config.js keys

### ISSUE THREAD

**Issue by funblaster22** [mkossoris/YTM-Plus#34]
I noticed that `config.js` is excluded in the `.gitignore` file, but I wanted to make sure you were aware these secrets are still available in the bundled chrome extension. I know it may not be realistically possible to fix this without using an additional server, and it's unlikely that many people would be doing this. It just made cloning the project a little surprising 😄. If you want more info, I can send it to you privately.

**Comment by mkossoris** [comment]
Hey @funblaster22! I am aware of this issue, and you're correct - unfortunately there's no great way to go about fixing this without a server in the middle to proxy requests to the other services, and as this is an unpaid chrome extension, it's hard to justify paying for server costs.

That said, I am working on a full revamp of this extension and new feature for the extension that will include some server work and corresponding monetization, so I may move these calls to be proxied at that point :).

**Comment by mkossoris** [comment]
Btw I'm gonna go ahead and delete this issue, as it is a security concern with the current implementation. While it's not particularly hard for someone to figure out how to get these keys, I'd rather not have a public issue about it haha
